site_name: Laulom Anthony
site_url: https://www.laulom.io
theme:
  features:
    - toc.integrate
    - navigation.top
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
plugins: []
extra_css:
  - assets/custom.css
extra_javascript:
  - assets/print-button.js
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg